### ISSUE TITLE
When server response multiple Set-Cookie headers, undici throws TypeError: obj[key].push is not a function

### ISSUE THREAD

**Issue by clarkorz** [mcollina/undici#5]
If server response contains  multiple `set-cookie` headers, undici throws  following error:

```
TypeError: obj[key].push is not a function
    at parseHeaders (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:341:16)
    at HTTPParser.Client.parser.(anonymous function) (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:219:18)
    at HTTPParser.HEADER (/Users/wangshuo/Projects/ksite_webapps/node_modules/http-parser-js/http-parser.js:335:58)
    at HTTPParser.execute (/Users/wangshuo/Projects/ksite_webapps/node_modules/http-parser-js/http-parser.js:111:27)
    at Client.[read] (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:268:19)
    at Socket.Client.(anonymous function) (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:240:18)
    at Object.onceWrapper (events.js:313:30)
    at ZoneDelegate.invokeTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:496:34)
    at Socket.ZoneTask.invoke (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:485:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by mcollina** [comment]
Thanks for reporting, it should be fixed in 0.3.3.
