### ISSUE TITLE
undici doesn't response "curl -I", then if "curl" again, undici will crash

### ISSUE THREAD

**Issue by clarkorz** [mcollina/undici#7]
I use fastify-http-proxy with undici. When `curl -I http://127.0.0.1:5000/proxy/abc`, curl doesn't receive any response (bash keep waiting). Then, if I `curl http://127.0.0.1:5000/proxy/abc`, which not include `-I`, undici will crash with following error:

```
11:19:59 ✨ incoming request HEAD xxx /proxy/abc
11:19:59 ✨ fetching from remote server
11:19:59 ✨ response received
-----> here should be `request completed 25ms`, but missing
11:20:10 ✨ incoming request GET xxx /proxy/abc
11:20:10 ✨ fetching from remote server
TypeError: Cannot read property 'push' of null
    at HTTPParser.Client.parser.(anonymous function) (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:229:22)
    at HTTPParser.BODY_RAW (/Users/wangshuo/Projects/ksite_webapps/node_modules/http-parser-js/http-parser.js:408:32)
    at HTTPParser.execute (/Users/wangshuo/Projects/ksite_webapps/node_modules/http-parser-js/http-parser.js:111:27)
    at Client.[read] (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:268:19)
    at Socket.Client.(anonymous function) (/Users/wangshuo/Projects/ksite_webapps/node_modules/undici/lib/client.js:240:18)
    at Object.onceWrapper (events.js:313:30)
    at ZoneDelegate.invokeTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:496:34)
    at Socket.ZoneTask.invoke (/Users/wangshuo/Projects/ksite_webapps/node_modules/zone.js/dist/zone-node.js:485:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

```

**Comment by mcollina** [comment]
fixed in #9
